# Generated by Django 5.2.7 on 2025-12-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='წელი')),
                ('month', models.IntegerField(verbose_name='თვე')),
                ('day', models.IntegerField(verbose_name='დღე')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
