# Generated by Django 5.2.7 on 2025-12-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='სახელი')),
                ('last_name', models.CharField(max_length=100, verbose_name='გვარი')),
                ('birth_date', models.DateField(verbose_name='დაბადების თარიღი')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
